"""create plant_knowledge table

Revision ID: 6f4a510a3cff
Revises: d0d18e95959c
Create Date: 2026-06-11 02:47:27.461691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4a510a3cff'
down_revision = 'd0d18e95959c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=False),
    sa.Column('common_name', sa.String(length=200), nullable=True),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('genus', sa.String(length=100), nullable=True),
    sa.Column('profile_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('times_looked_up', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plant_knowledge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_knowledge_scientific_name'), ['scientific_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_knowledge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_knowledge_scientific_name'))

    op.drop_table('plant_knowledge')
    # ### end Alembic commands ###
